### ISSUE TITLE
How to implement for 4.5 framework versions

### ISSUE THREAD

**Issue by snspvd** [lilpug/ASP.NET-Core-Impersonation#2]
How to implement for 4.5 framework versions?

**Comment by lilpug** [comment]
Hi,

Appologies for the delayed comment, i really need to set notifications up.

As state in the readme for the project this is for 4.6 and above due to the dll dependencies.

"This library is for the ASP.NET Core (.NET Framework 4.6+) version only, this is due to the library utilising the advapi32.dll for the internal impersonation capability."

Hope this helps answer your question.
